/**
 * @module readme/template
 * Produces README.md from the registry so asset references, sizes and links
 * can never drift from what the build generates.
 */

import type { AssetRenderer, ProfileData } from '../core/types.ts';
import { picture } from './picture.ts';

/** Width of a half-row image; leaves room for the inline gap between two. */
const HALF = '48.4%';

function byId(renderers: readonly AssetRenderer[], id: string): AssetRenderer {
  const renderer = renderers.find((candidate) => candidate.id === id);
  if (!renderer) throw new Error(`No renderer registered with id "${id}"`);
  return renderer;
}

function projectGrid(
  data: Omit<ProfileData, 'stats'>,
  renderers: readonly AssetRenderer[],
): string {
  return twoColumns(
    data.projects.map((project) =>
      picture(byId(renderers, `project-${project.repo.toLowerCase()}`), {
        alt: project.repo,
        href: `https://github.com/${data.profile.login}/${project.repo}`,
        width: HALF,
      }),
    ),
  );
}

function contactRow(data: Omit<ProfileData, 'stats'>, renderers: readonly AssetRenderer[]): string {
  return data.profile.links
    .map((link) =>
      picture(byId(renderers, `contact-${link.id}`), {
        alt: link.label,
        href: link.url,
        height: 66,
      }),
    )
    .join('\n');
}

/** Inline gap between two half-width images; with the surrounding line breaks this is about 16px, matching the row gap. */
const GAP = '&nbsp;&nbsp;';

/**
 * Two images per row without a table. GitHub draws borders around table
 * cells (and shows them as empty boxes while images load), so each row is a
 * centred paragraph of two inline images. One paragraph per row keeps every
 * vertical gap equal to the paragraph margin.
 */
function twoColumns(cells: readonly string[]): string {
  const rows: string[] = [];
  for (let i = 0; i < cells.length; i += 2) {
    const pair = [cells[i], cells[i + 1]].filter((cell): cell is string => cell !== undefined);
    rows.push(`<p align="center">\n${pair.join(`\n${GAP}\n`)}\n</p>`);
  }
  return rows.join('\n\n');
}

/**
 * The complete README: hero, activity pair, project grid, contribution
 * calendar, contact buttons. No headings; spacing alone separates blocks and
 * the assets carry their own titles.
 */
export function readmeMarkdown(
  data: Omit<ProfileData, 'stats'>,
  renderers: readonly AssetRenderer[],
): string {
  const { profile } = data;
  return `<!-- Generated by \`npm run readme\` from src/readme/template.ts. Edit the template, not this file. -->

<p align="center">
${picture(byId(renderers, 'hero'), { alt: `${profile.name} — ${profile.title}`, width: '100%' })}
</p>

${twoColumns([
  picture(byId(renderers, 'stats'), { alt: 'GitHub activity', width: HALF }),
  picture(byId(renderers, 'languages'), { alt: 'Top languages', width: HALF }),
])}

${projectGrid(data, renderers)}

<p align="center">
${picture(byId(renderers, 'contributions'), { alt: 'Contribution calendar', width: '100%' })}
</p>

<p align="center">
${contactRow(data, renderers)}
</p>
`;
}
